"use client"

import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Navigation } from "@/components/navigation"
import { Footer } from "@/components/footer"
import { DashboardPreview } from "@/components/dashboard-preview"
import { Chatbot } from "@/components/chatbot"
import { SettingsPanel } from "@/components/settings-panel"
import {
  BarChart3,
  FileText,
  Zap,
  Shield,
  Users,
  TrendingUp,
  ArrowRight,
  CheckCircle2,
  Star,
  Play,
} from "lucide-react"

const stats = [
  { value: "10h+", label: "saved per audit" },
  { value: "98%", label: "client satisfaction" },
  { value: "3x", label: "more clients retained" },
  { value: "500+", label: "agencies using it" },
]

const features = [
  {
    icon: BarChart3,
    title: "Automatic Analysis",
    description: "Connect your data sources and get comprehensive analysis in just a few clicks.",
  },
  {
    icon: FileText,
    title: "Professional PDF Export",
    description: "Generate customized PDF reports with your agency branding and colors.",
  },
  {
    icon: Zap,
    title: "AI Recommendations",
    description: "Get concrete, actionable suggestions generated by our artificial intelligence.",
  },
  {
    icon: Shield,
    title: "Secure Multi-client",
    description: "Manage all your clients from one interface with 100% secure data.",
  },
  {
    icon: Users,
    title: "Team Collaboration",
    description: "Invite your team members and work together on client audits.",
  },
  {
    icon: TrendingUp,
    title: "Progress Tracking",
    description: "Compare performance over time and show progress to your clients.",
  },
]

const testimonials = [
  {
    quote: "AuditPro has cut our report time by 3x. A must-have for any marketing agency.",
    author: "Sarah Johnson",
    role: "Director, WebPulse Agency",
    rating: 5,
  },
  {
    quote: "The AI recommendations are stunning. My clients are impressed by the quality of the audits.",
    author: "Michael Chen",
    role: "Freelance SEO Consultant",
    rating: 5,
  },
  {
    quote: "The PDF export is perfect for our presentations. Intuitive interface, exactly what we needed.",
    author: "Emily Davis",
    role: "CEO, Digital Factory",
    rating: 5,
  },
]

export default function HomePage() {
  return (
    <div className="min-h-screen bg-background">
      <Navigation />

      {/* Hero Section */}
      <section className="relative pt-32 pb-20 md:pt-40 md:pb-32 overflow-hidden">
        {/* Background Effects */}
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-primary/20 via-background to-background" />
        <div className="absolute top-20 left-1/4 h-72 w-72 rounded-full bg-primary/10 blur-3xl animate-pulse" />
        <div className="absolute top-40 right-1/4 h-96 w-96 rounded-full bg-chart-2/10 blur-3xl animate-pulse" style={{ animationDelay: "1s" }} />
        
        <div className="relative mx-auto max-w-7xl px-6">
          <div className="mx-auto max-w-3xl text-center">
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-4 py-2 text-sm text-primary animate-in fade-in slide-in-from-bottom-4 duration-700">
              <span className="relative flex h-2 w-2">
                <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-primary opacity-75" />
                <span className="relative inline-flex h-2 w-2 rounded-full bg-primary" />
              </span>
              New: Advanced AI Recommendations
            </div>
            <h1 className="text-balance text-4xl font-bold tracking-tight text-foreground md:text-6xl lg:text-7xl animate-in fade-in slide-in-from-bottom-4 duration-700" style={{ animationDelay: "100ms" }}>
              Generate client audits{" "}
              <span className="bg-gradient-to-r from-primary via-chart-2 to-primary bg-clip-text text-transparent">in minutes</span>
            </h1>
            <p className="mt-6 text-pretty text-lg text-muted-foreground md:text-xl animate-in fade-in slide-in-from-bottom-4 duration-700" style={{ animationDelay: "200ms" }}>
              The all-in-one platform for marketing agencies, SEO consultants, and freelancers. 
              Analyze, visualize, and present your client data like never before.
            </p>
            <div className="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row animate-in fade-in slide-in-from-bottom-4 duration-700" style={{ animationDelay: "300ms" }}>
              <Button size="lg" className="group shadow-lg shadow-primary/25 transition-all hover:shadow-xl hover:shadow-primary/30" asChild>
                <Link href="/contact">
                  Start Free
                  <ArrowRight className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1" />
                </Link>
              </Button>
              <Button size="lg" variant="outline" className="group bg-transparent" asChild>
                <Link href="/dashboard">
                  <Play className="mr-2 h-4 w-4 transition-transform group-hover:scale-110" />
                  View Demo
                </Link>
              </Button>
            </div>
          </div>

          {/* Stats */}
          <div className="mt-20 grid grid-cols-2 gap-6 md:grid-cols-4 animate-in fade-in slide-in-from-bottom-4 duration-700" style={{ animationDelay: "400ms" }}>
            {stats.map((stat, index) => (
              <div 
                key={stat.label} 
                className="group relative text-center p-6 rounded-2xl border border-border/50 bg-card/50 backdrop-blur-sm transition-all hover:border-primary/50 hover:bg-card"
              >
                <div className="absolute inset-0 rounded-2xl bg-gradient-to-br from-primary/5 to-transparent opacity-0 transition-opacity group-hover:opacity-100" />
                <p className="relative text-3xl font-bold text-primary md:text-4xl">{stat.value}</p>
                <p className="relative mt-1 text-sm text-muted-foreground">{stat.label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Dashboard Preview Section */}
      <section className="py-20 md:py-32 relative">
        <div className="absolute inset-0 bg-gradient-to-b from-background via-card/30 to-background" />
        <div className="relative mx-auto max-w-7xl px-6">
          <div className="mb-12 text-center">
            <h2 className="text-balance text-3xl font-bold text-foreground md:text-4xl lg:text-5xl">
              A powerful dashboard for all your clients
            </h2>
            <p className="mt-4 text-lg text-muted-foreground">
              Visualize performance, identify opportunities, and impress your clients.
            </p>
          </div>
          <div className="relative">
            <div className="absolute -inset-4 rounded-3xl bg-gradient-to-r from-primary/20 via-chart-2/20 to-primary/20 blur-2xl opacity-50" />
            <div className="relative">
              <DashboardPreview />
            </div>
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section className="py-20 md:py-32">
        <div className="mx-auto max-w-7xl px-6">
          <div className="mb-12 text-center">
            <h2 className="text-balance text-3xl font-bold text-foreground md:text-4xl lg:text-5xl">
              Everything you need for your audits
            </h2>
            <p className="mt-4 text-lg text-muted-foreground">
              A complete suite of tools to analyze, present, and convince.
            </p>
          </div>
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {features.map((feature, index) => (
              <div
                key={feature.title}
                className="group relative rounded-2xl border border-border/50 bg-card/50 p-6 transition-all duration-300 hover:border-primary/50 hover:bg-card hover:shadow-xl hover:shadow-primary/5"
                style={{ animationDelay: `${index * 100}ms` }}
              >
                <div className="absolute inset-0 rounded-2xl bg-gradient-to-br from-primary/5 to-transparent opacity-0 transition-opacity group-hover:opacity-100" />
                <div className="relative">
                  <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br from-primary/20 to-primary/5 text-primary transition-transform group-hover:scale-110">
                    <feature.icon className="h-6 w-6" />
                  </div>
                  <h3 className="mb-2 text-lg font-semibold text-foreground">{feature.title}</h3>
                  <p className="text-sm text-muted-foreground">{feature.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-20 md:py-32 relative">
        <div className="absolute inset-0 bg-gradient-to-b from-background via-card/30 to-background" />
        <div className="relative mx-auto max-w-7xl px-6">
          <div className="mb-12 text-center">
            <h2 className="text-balance text-3xl font-bold text-foreground md:text-4xl lg:text-5xl">
              Trusted by agencies worldwide
            </h2>
            <p className="mt-4 text-lg text-muted-foreground">
              Discover what our users say about AuditPro.
            </p>
          </div>
          <div className="grid gap-6 md:grid-cols-3">
            {testimonials.map((testimonial, index) => (
              <div
                key={testimonial.author}
                className="group relative rounded-2xl border border-border/50 bg-card/50 p-6 transition-all duration-300 hover:border-primary/50 hover:bg-card hover:shadow-xl hover:shadow-primary/5"
              >
                <div className="absolute inset-0 rounded-2xl bg-gradient-to-br from-primary/5 to-transparent opacity-0 transition-opacity group-hover:opacity-100" />
                <div className="relative">
                  <div className="mb-4 flex gap-1">
                    {Array.from({ length: testimonial.rating }).map((_, i) => (
                      <Star key={i} className="h-4 w-4 fill-chart-3 text-chart-3" />
                    ))}
                  </div>
                  <p className="mb-4 text-foreground">{`"${testimonial.quote}"`}</p>
                  <div>
                    <p className="font-semibold text-foreground">{testimonial.author}</p>
                    <p className="text-sm text-muted-foreground">{testimonial.role}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 md:py-32">
        <div className="mx-auto max-w-7xl px-6">
          <div className="relative overflow-hidden rounded-3xl border border-border/50 bg-gradient-to-br from-card via-card to-primary/5 p-8 text-center md:p-16">
            <div className="absolute top-0 left-1/2 -translate-x-1/2 h-px w-1/2 bg-gradient-to-r from-transparent via-primary/50 to-transparent" />
            <div className="absolute bottom-0 left-1/2 -translate-x-1/2 h-px w-1/2 bg-gradient-to-r from-transparent via-primary/50 to-transparent" />
            <h2 className="text-balance text-3xl font-bold text-foreground md:text-4xl lg:text-5xl">
              Ready to transform your client audits?
            </h2>
            <p className="mt-4 text-lg text-muted-foreground">
              Join over 500 agencies using AuditPro to impress their clients and prove their ROI.
            </p>
            <div className="mt-8 flex flex-col items-center justify-center gap-4 sm:flex-row">
              <Button size="lg" className="group shadow-lg shadow-primary/25" asChild>
                <Link href="/contact">
                  Start Free
                  <ArrowRight className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1" />
                </Link>
              </Button>
              <Button size="lg" variant="outline" className="bg-transparent" asChild>
                <Link href="/pricing">
                  View Pricing
                </Link>
              </Button>
            </div>
            <div className="mt-6 flex flex-wrap items-center justify-center gap-6 text-sm text-muted-foreground">
              <span className="flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-primary" />
                Free plan available
              </span>
              <span className="flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-primary" />
                No credit card required
              </span>
              <span className="flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-primary" />
                Cancel anytime
              </span>
            </div>
          </div>
        </div>
      </section>

      <Footer />
      <Chatbot />
      <SettingsPanel />
    </div>
  )
}
